name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: List devices
      run: xcrun simctl list

    - name: Build and test
      run: xcodebuild clean build test -workspace Quizzy.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.4,name=iPhone 12" CODE_SIGNING_REQUIRED=NO
